# Generated by Django 4.0 on 2021-12-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=200)),
                ('tanggal_lahir', models.CharField(max_length=200)),
                ('tanggal_registrasi', models.DateField(auto_now_add=True)),
                ('berlaku_hingga', models.CharField(max_length=200)),
                ('tipe_anggota', models.TextField(max_length=200)),
                ('pekerjaan', models.TextField(max_length=200)),
                ('alamat', models.TextField(max_length=200)),
                ('jenis_kelamin', models.TextField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200)),
                ('negara', models.TextField(max_length=200)),
                ('no_hp', models.IntegerField(default=0)),
                ('email', models.TextField(max_length=200)),
                ('instansi', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=200)),
                ('edisi', models.CharField(max_length=200)),
                ('info_detail_spesifikasi', models.CharField(max_length=200)),
                ('tipe_isi', models.CharField(choices=[('fiksi', 'fiksi'), ('pendidikan', 'pendidikan')], max_length=200)),
                ('tipe_media', models.CharField(choices=[('cetak', 'cetak'), ('online', 'online')], max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('penerbit', models.CharField(max_length=200)),
                ('tahun_terbit', models.IntegerField()),
                ('tempat_terbit', models.CharField(max_length=200)),
                ('diskripsi_fisik', models.CharField(max_length=200)),
                ('klasifikasi', models.CharField(max_length=200)),
                ('no_panggil', models.IntegerField()),
                ('bahasa', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('opac', models.CharField(choices=[('tampil', 'tampil'), ('sembunyi', 'sembunyi')], max_length=200)),
                ('beranda', models.CharField(choices=[('tampil', 'tampil'), ('sembunyi', 'sembunyi')], max_length=200)),
            ],
        ),
    ]
