# Generated by Django 3.2.8 on 2022-01-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=200)),
                ('tanggal_lahir', models.CharField(max_length=200)),
                ('tanggal_registrasi', models.DateField(auto_now_add=True)),
                ('berlaku_hingga', models.CharField(max_length=200)),
                ('tipe_anggota', models.CharField(choices=[('Mahasiswa', 'Mahasiswa'), ('Umum', 'Umum'), ('Santri', 'Santri')], max_length=200)),
                ('pekerjaan', models.TextField(max_length=200)),
                ('alamat', models.TextField(max_length=200)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200)),
                ('negara', models.TextField(max_length=200)),
                ('no_hp', models.BigIntegerField()),
                ('email', models.TextField(max_length=200)),
                ('instansi', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=200)),
                ('edisi', models.CharField(max_length=200)),
                ('info_detail_spesifikasi', models.CharField(max_length=200)),
                ('tipe_isi', models.CharField(choices=[('fiksi', 'fiksi'), ('pendidikan', 'pendidikan')], max_length=200)),
                ('tipe_media', models.CharField(choices=[('cetak', 'cetak'), ('online', 'online')], max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('penerbit', models.CharField(max_length=200)),
                ('tahun_terbit', models.IntegerField()),
                ('tempat_terbit', models.CharField(max_length=200)),
                ('diskripsi_fisik', models.CharField(max_length=200)),
                ('klasifikasi', models.CharField(max_length=200)),
                ('bahasa', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('opac', models.CharField(choices=[('tampil', 'tampil'), ('sembunyi', 'sembunyi')], max_length=200)),
                ('beranda', models.CharField(choices=[('tampil', 'tampil'), ('sembunyi', 'sembunyi')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_panggil', models.CharField(max_length=200)),
                ('kode_inventaris', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=200)),
                ('exemplar', models.CharField(max_length=200)),
                ('jumlah_eksemplar', models.CharField(max_length=200)),
                ('tgl_pesan', models.CharField(max_length=200)),
                ('tgl_terima', models.CharField(max_length=200)),
                ('promosi', models.CharField(choices=[('tampil', 'tampil'), ('sembunyi', 'sembunyi')], max_length=200)),
                ('id_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='main2.buku')),
            ],
        ),
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('tanggal_lahir', models.DateField()),
                ('jabatan', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('no_hp', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pinjam', models.DateField(auto_now=True)),
                ('tgl_kembali', models.CharField(max_length=200)),
                ('denda', models.IntegerField(blank=True, null=True)),
                ('alamat', models.TextField(max_length=200)),
                ('transaksi', models.CharField(choices=[('Ditempat', 'Ditempat'), ('Diambil', 'Diambil'), ('Dikirim', 'Dikirim')], max_length=200)),
                ('id_anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='main2.anggota')),
                ('id_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputan1', to='main2.buku')),
                ('id_exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isi', to='main2.exemplar')),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengisi', to='main2.karyawan')),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputan', to='main2.buku')),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data1', to='main2.anggota')),
                ('no_panggil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode', to='main2.exemplar')),
            ],
        ),
        migrations.AddField(
            model_name='exemplar',
            name='id_karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aksi', to='main2.karyawan'),
        ),
        migrations.AddField(
            model_name='exemplar',
            name='judul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputan2', to='main2.buku'),
        ),
    ]
