# Generated by Django 3.2.8 on 2021-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='denda',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='tgl_kembali',
            field=models.CharField(max_length=200),
        ),
    ]
