# Generated by Django 3.2.8 on 2022-01-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemplar',
            old_name='id_buku',
            new_name='judul',
        ),
    ]
