# Generated by Django 3.2.8 on 2021-12-23 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='kode_pinjam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main2.buku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buku',
            name='no_panggil',
            field=models.CharField(max_length=200),
        ),
    ]
