# Generated by Django 3.2.8 on 2022-01-01 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='judul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inps', to='main2.buku'),
        ),
    ]
