# Generated by Django 3.2.8 on 2021-12-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0002_rename_berlaku_hingga_anggota_berlaku_hingga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='no_hp',
            field=models.IntegerField(max_length=200),
        ),
    ]
