# Generated by Django 3.2.8 on 2021-12-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0002_auto_20211223_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinjam',
            old_name='kode_pinjam',
            new_name='no_pang',
        ),
    ]
