# Generated by Django 3.2.8 on 2021-12-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0002_auto_20211229_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='denda',
            field=models.IntegerField(),
        ),
    ]
