# Generated by Django 3.2.8 on 2022-01-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0002_alter_exemplar_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='judul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main2.buku'),
        ),
    ]
