# Generated by Django 3.2.8 on 2021-12-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0003_alter_anggota_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='no_hp',
            field=models.IntegerField(),
        ),
    ]
