# Generated by Django 3.2.8 on 2022-01-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0003_alter_exemplar_judul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplar',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='pinjam',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='pinjam',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='pinjam',
            name='no_panggil',
        ),
        migrations.AddField(
            model_name='anggota',
            name='id_karyawan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ak', to='main2.karyawan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buku',
            name='id_karyawan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='aks', to='main2.karyawan'),
            preserve_default=False,
        ),
    ]
