# Generated by Django 3.2.8 on 2021-12-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0003_alter_pinjam_denda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='denda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
