# Generated by Django 3.2.8 on 2021-12-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0004_alter_anggota_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='no_hp',
            field=models.IntegerField(max_length=200),
        ),
    ]
