# Generated by Django 3.2.8 on 2022-01-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0004_auto_20220101_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='id_karyawan',
        ),
    ]
