# Generated by Django 3.2.8 on 2022-01-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0005_remove_buku_id_karyawan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='id_karyawan',
        ),
    ]
