# Generated by Django 3.2.8 on 2021-12-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0006_alter_anggota_no_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='jenis_kelamin',
        ),
    ]
