# Generated by Django 4.0 on 2022-01-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0006_remove_anggota_id_karyawan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemplar',
            old_name='exemplar',
            new_name='jumlah_exemplar',
        ),
        migrations.RenameField(
            model_name='exemplar',
            old_name='jumlah_eksemplar',
            new_name='kode_exemplar',
        ),
    ]
