# Generated by Django 3.2.8 on 2021-12-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0007_remove_anggota_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='jenis_kelamin',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
