# Generated by Django 3.2.8 on 2021-12-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0008_anggota_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='jenis_kelamin',
            field=models.TextField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='no_hp',
            field=models.IntegerField(default=0),
        ),
    ]
