# Generated by Django 3.2.8 on 2021-12-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0010_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='cover',
            field=models.ImageField(upload_to='cars'),
        ),
    ]
