# Generated by Django 3.2.8 on 2021-12-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0011_alter_buku_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='anggota_sejak',
        ),
        migrations.AlterField(
            model_name='anggota',
            name='tanggal_registrasi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
