# Generated by Django 3.2.8 on 2021-12-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0012_auto_20211209_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='beranda',
            field=models.CharField(choices=[('tampil', 'tampil'), ('sembunyi', 'sembunyi')], max_length=200),
        ),
        migrations.AlterField(
            model_name='buku',
            name='opac',
            field=models.CharField(choices=[('tampil', 'tampil'), ('sembunyi', 'sembunyi')], max_length=200),
        ),
    ]
