# Generated by Django 3.2.8 on 2021-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0013_auto_20211213_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
