# Generated by Django 3.2.8 on 2021-12-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0014_alter_buku_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
