# Generated by Django 3.2.8 on 2021-11-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=200)),
                ('ttl', models.CharField(max_length=200)),
                ('jenis_kelamin', models.TextField(max_length=200)),
                ('pekerjaan', models.TextField(max_length=200)),
                ('alamat', models.TextField(max_length=200)),
                ('no_hp', models.IntegerField()),
                ('email', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField(max_length=200)),
                ('pengarang', models.TextField(max_length=200)),
                ('edisi', models.CharField(max_length=200)),
                ('terbit', models.TextField(max_length=200)),
                ('tempat_terbit', models.TextField(max_length=200)),
                ('Deskripsi_fisik', models.TextField(max_length=200)),
                ('judul_seri', models.TextField(max_length=200)),
                ('klasifikasi', models.TextField(max_length=200)),
                ('No_panggil', models.TextField(max_length=200)),
                ('Subyek', models.TextField(max_length=200)),
                ('bahasa', models.TextField(max_length=200)),
                ('gambar_sampul', models.TextField(max_length=200)),
            ],
        ),
    ]
