# Generated by Django 3.2.8 on 2021-12-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersprof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=200)),
                ('instansi', models.CharField(max_length=200)),
                ('pekerjaan', models.CharField(max_length=200)),
                ('negara', models.CharField(max_length=200)),
                ('alamat', models.DateField(auto_now_add=True)),
                ('no_hp', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pasword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='usulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=200)),
                ('tahun_terbit', models.DateField(auto_now_add=True)),
                ('penerbit', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('harga', models.CharField(max_length=200)),
            ],
        ),
    ]
