# Generated by Django 3.2.8 on 2021-12-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usulan',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usulan',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='usulan',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='usulan',
            name='nama',
        ),
    ]
