# Generated by Django 3.2.8 on 2021-11-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buku',
        ),
        migrations.AddField(
            model_name='anggota',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
