# Generated by Django 3.2.8 on 2022-01-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211231_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usersprof',
        ),
    ]
