# Generated by Django 3.2.8 on 2021-11-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211129_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggota',
            old_name='ttl',
            new_name='tanggal_lahir',
        ),
    ]
