# Generated by Django 3.2.8 on 2021-11-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_ttl_anggota_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='instansi',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
