# Generated by Django 3.2.8 on 2021-11-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_anggota_instansi'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='negara',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
