# Generated by Django 3.2.8 on 2021-12-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_anggota_negara'),
    ]

    operations = [
        migrations.DeleteModel(
            name='anggota',
        ),
    ]
