# Generated by Django 4.0 on 2021-12-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_delete_anggota'),
    ]

    operations = [
        migrations.CreateModel(
            name='usulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('judul', models.CharField(max_length=200)),
                ('pengarang', models.CharField(max_length=200)),
                ('tahun_penerbit', models.DateField(auto_now_add=True)),
                ('penerbit', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('Harga', models.CharField(max_length=200)),
            ],
        ),
    ]
