# Generated by Django 4.0 on 2021-12-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usulan',
            old_name='tahun_penerbit',
            new_name='tahun_terbit',
        ),
    ]
