# Generated by Django 4.0 on 2021-12-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_tahun_penerbit_usulan_tahun_terbit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usulan',
            old_name='Harga',
            new_name='harga',
        ),
    ]
