# Generated by Django 4.0 on 2021-12-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_harga_usulan_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=200)),
                ('instansi', models.CharField(max_length=200)),
                ('pekerjaan', models.CharField(max_length=200)),
                ('negara', models.CharField(max_length=200)),
                ('alamat', models.DateField(auto_now_add=True)),
                ('no_hp', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pasword', models.CharField(max_length=200)),
            ],
        ),
    ]
